### ISSUE TITLE
look further into injection materials

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-validation#6]
Gauge presence of this info within assets, and aggregate a list of existing materials used to assess for further research.

**Comment by saskiad** [comment]
@dyf I'm a little confused by this task. We haven't been ingesting injection materials because there's no consistent way to enter them. There are some from early experiments, but it's largely empty. What's the goal for this?

**Comment by jtyoung84** [comment]
@Sun-flow Can you verify that this is an issue?

**Comment by Sun-flow** [comment]
> @Sun-flow Can you verify that this is an issue?

@jtyoung84 @dyf Not sure what the "issue" is here, but I have done looks into Inj material presence. I am going to be pulling some procedures tomorrow for use in the procedures upgrader, so I will aggregate some more info while doing that.

**Comment by mekhlakapoor** [comment]
Moving this issue back onto our project board. @jtyoung84 feel free to remove it again if it doesn't belong there but add a note for why
